# Generated by Django 3.1 on 2021-01-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('mic_mute', models.CharField(blank=True, max_length=30, null=True)),
                ('lang', models.CharField(blank=True, max_length=30, null=True)),
                ('fadeOnTime', models.IntegerField(default=0)),
                ('serial', models.CharField(blank=True, max_length=30, null=True)),
                ('configuredAmazon', models.CharField(blank=True, max_length=30, null=True)),
                ('brightness', models.IntegerField(default=0)),
                ('downloaded', models.CharField(blank=True, max_length=30, null=True)),
                ('residentialRoomId', models.CharField(blank=True, max_length=30, null=True)),
                ('env', models.IntegerField(default=0)),
                ('timeZoneName', models.CharField(blank=True, max_length=30, null=True)),
                ('identify', models.IntegerField(default=0)),
                ('blink', models.IntegerField(default=0)),
                ('linkData', models.CharField(blank=True, max_length=30, null=True)),
                ('loadType', models.IntegerField(default=0)),
                ('isRandomEnabled', models.BooleanField(default=False)),
                ('ota', models.BooleanField(default=False)),
                ('otaStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('connected', models.BooleanField(default=False)),
                ('allowLocalCommands', models.CharField(blank=True, max_length=30, null=True)),
                ('long', models.CharField(blank=True, max_length=30, null=True)),
                ('presetLevel', models.IntegerField(default=0)),
                ('timeZone', models.IntegerField(default=0)),
                ('buttonData', models.CharField(blank=True, max_length=30, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('apply_ota', models.CharField(blank=True, max_length=30, null=True)),
                ('cloud_ota', models.CharField(blank=True, max_length=30, null=True)),
                ('canSetLevel', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('customType', models.CharField(blank=True, max_length=30, null=True)),
                ('autoOffTime', models.IntegerField(default=0)),
                ('programData', models.CharField(blank=True, max_length=30, null=True)),
                ('resKey', models.CharField(blank=True, max_length=30, null=True)),
                ('resOcc', models.CharField(blank=True, max_length=30, null=True)),
                ('lat', models.CharField(blank=True, max_length=30, null=True)),
                ('includeInRoomOnOff', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('power', models.BooleanField(default=False, verbose_name='On')),
                ('random', models.BooleanField(default=False)),
                ('lastUpdated', models.CharField(blank=True, max_length=30, null=True)),
                ('dimLED', models.IntegerField(default=0)),
                ('audio_cue', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('fadeOffTime', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('logging', models.CharField(blank=True, max_length=30, null=True)),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
                ('maxLevel', models.IntegerField(default=0)),
                ('statusLED', models.IntegerField(default=0)),
                ('localIP', models.CharField(blank=True, max_length=30, null=True)),
                ('rssi', models.CharField(blank=True, max_length=30, null=True)),
                ('isAlexaDiscoverable', models.BooleanField(default=False)),
                ('created', models.CharField(blank=True, max_length=30, null=True)),
                ('mac', models.CharField(blank=True, max_length=30, null=True)),
                ('dstOffset', models.IntegerField(default=0)),
                ('dstEnd', models.IntegerField(default=0)),
                ('residenceId', models.IntegerField(default=0)),
                ('minLevel', models.IntegerField(default=0)),
                ('dstStart', models.IntegerField(default=0)),
                ('onTime', models.IntegerField(default=0)),
                ('connectedTimestamp', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
