# Generated by Django 3.1 on 2021-01-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name_plural': 'Switches'},
        ),
    ]
