# Generated by Django 3.1 on 2021-01-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('type', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('motion_detector', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('armed_state', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
