# Generated by Django 3.1 on 2021-01-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=False, verbose_name='Usable By HomeAuto')),
                ('directory', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
