# Generated by Django 3.1 on 2021-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
    ]
