# Generated by Django 3.1 on 2021-01-13 23:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField(default=0)),
                ('mode', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('current_activity', models.CharField(max_length=6)),
                ('htsp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('clsp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fan', models.CharField(max_length=6)),
                ('hold', models.BooleanField(default=False)),
                ('hold_time', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('vaca_running', models.BooleanField(default=False)),
                ('heat_mode', models.CharField(max_length=30)),
                ('temp_unit', models.CharField(max_length=1)),
                ('filtrlvl', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humlvl', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humid', models.BooleanField(default=False)),
                ('infinity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.infinity')),
            ],
        ),
        migrations.CreateModel(
            name='InfProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('clsp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('htsp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fan', models.CharField(max_length=4)),
                ('infinity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.infinity')),
            ],
        ),
        migrations.CreateModel(
            name='InfActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('activity', models.CharField(max_length=6)),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0)),
                ('period', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
                ('infinity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.infinity')),
            ],
        ),
    ]
