# Generated by Django 3.1 on 2021-01-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('ip', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=60)),
                ('count_down_lights', models.BooleanField(default=False)),
                ('alarm_use', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('on', models.BooleanField(default=False)),
                ('hue', models.IntegerField(default=0)),
                ('effect', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('bri', models.IntegerField(default=0)),
                ('sat', models.IntegerField(default=0)),
                ('ct', models.IntegerField(default=0)),
                ('xy', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('alert', models.CharField(blank=True, default='none', max_length=30, null=True)),
                ('colormode', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hue.bridge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('on', models.BooleanField(default=False)),
                ('hue', models.IntegerField(default=0)),
                ('effect', models.CharField(default='', max_length=30)),
                ('bri', models.IntegerField(default=0)),
                ('sat', models.IntegerField(default=0)),
                ('ct', models.IntegerField(default=0)),
                ('xy', models.CharField(default='', max_length=30)),
                ('alert', models.CharField(default='none', max_length=30)),
                ('colormode', models.CharField(default='', max_length=30)),
                ('reachable', models.BooleanField(default=False)),
                ('type', models.CharField(default='', max_length=30)),
                ('modelid', models.CharField(default='', max_length=15)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hue.bridge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SceneLightstate',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bri', models.IntegerField(default=0)),
                ('xy', models.CharField(default='', max_length=30)),
                ('sat', models.IntegerField(default=0)),
                ('ct', models.IntegerField(default=0)),
                ('on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=30)),
                ('modelid', models.CharField(default='', max_length=15)),
                ('productname', models.CharField(blank=True, default='', max_length=30)),
                ('lastupdated', models.DateTimeField(blank=True)),
                ('dark', models.BooleanField(default=False)),
                ('daylight', models.BooleanField(default=False)),
                ('lightlevel', models.IntegerField(blank=True, default=0)),
                ('temperature', models.IntegerField(blank=True, default=0)),
                ('presence', models.BooleanField(default=False)),
                ('on', models.BooleanField(default=False)),
                ('battery', models.IntegerField(blank=True, default=0)),
                ('reachable', models.BooleanField(default=False)),
                ('alert', models.CharField(blank=True, default='none', max_length=30)),
                ('ledindication', models.BooleanField(default=False)),
                ('sensitivity', models.IntegerField(blank=True, default=0)),
                ('sensitivitymax', models.IntegerField(blank=True, default=0)),
                ('tholddark', models.IntegerField(blank=True, default=0)),
                ('tholdoffset', models.IntegerField(blank=True, default=0)),
                ('motion_detector', models.BooleanField(default=False)),
                ('bridge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hue.bridge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('description', models.CharField(default='', max_length=30)),
                ('localtime', models.CharField(default='', max_length=30)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hue.bridge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=False, verbose_name='Discoverable By HomeAuto')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=30)),
                ('owner', models.CharField(default='', max_length=60)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hue.bridge')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hue.group')),
                ('lights', models.ManyToManyField(to='hue.Light')),
                ('lightstates', models.ManyToManyField(to='hue.SceneLightstate')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='lights',
            field=models.ManyToManyField(to='hue.Light'),
        ),
    ]
